# Generated by Django 2.0.5 on 2018-05-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('accountcode', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Account Code')),
                ('local_calling_area', models.CharField(blank=True, max_length=128, verbose_name='Local Calling Area')),
                ('pulse', models.PositiveSmallIntegerField(default=0, verbose_name='Pulse')),
                ('channels', models.PositiveSmallIntegerField(default=0, verbose_name='Channels')),
                ('inbound_rate', models.DecimalField(decimal_places=4, default=0.02, max_digits=4, verbose_name='Inbound Calling Rate')),
                ('inbound_tollfree_rate', models.DecimalField(decimal_places=4, default=0.03, max_digits=4, verbose_name='Inbound Tollfree Calling Rate')),
                ('outbound_rate', models.DecimalField(decimal_places=4, default=0.02, max_digits=4, verbose_name='Outbound Calling Rate')),
                ('canadian_ld_rate', models.DecimalField(decimal_places=4, default=0.02, max_digits=4, verbose_name='Canadian Long Distance Rate')),
                ('united_states_ld_rate', models.DecimalField(decimal_places=4, default=0.02, max_digits=4, verbose_name='American Long Distance Rate')),
                ('international_ld_rate', models.DecimalField(decimal_places=4, default=0.02, max_digits=4, verbose_name='International Long Distance Rate')),
                ('two_pass_billing', models.BooleanField(default=False, verbose_name='Do we need to run two-pass billing?')),
            ],
        ),
    ]
