# Generated by Django 2.0.3 on 2018-05-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_rates', '0005_auto_20180527_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndependentRate',
            fields=[
                ('e164_prefix', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='E.164-formatted prefixes without leading "+".')),
                ('destination', models.CharField(max_length=96, verbose_name='The call destination.')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Call rate.')),
            ],
            options={
                'verbose_name': 'independent rate',
                'verbose_name_plural': 'independent rates',
            },
        ),
        migrations.CreateModel(
            name='InternationalHighRate',
            fields=[
                ('e164_prefix', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='E.164-formatted prefixes without leading "+".')),
                ('destination', models.CharField(max_length=96, verbose_name='The call destination.')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Call rate.')),
            ],
            options={
                'verbose_name': 'international high rate',
                'verbose_name_plural': 'international high rates',
            },
        ),
        migrations.CreateModel(
            name='InternationalLowRate',
            fields=[
                ('e164_prefix', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='E.164-formatted prefixes without leading "+".')),
                ('destination', models.CharField(max_length=96, verbose_name='The call destination.')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Call rate.')),
            ],
            options={
                'verbose_name': 'international low rate',
                'verbose_name_plural': 'international low rates',
            },
        ),
        migrations.RenameModel(
            old_name='Rate',
            new_name='CustomerRate',
        ),
        migrations.AlterModelOptions(
            name='customerrate',
            options={'verbose_name': 'customer rate', 'verbose_name_plural': 'customer rates'},
        ),
    ]
