# Generated by Django 2.0.3 on 2018-05-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_rates', '0006_auto_20180529_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerrate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='independentrate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='internationalhighrate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='internationallowrate',
            options={},
        ),
    ]
