# Generated by Django 2.0.3 on 2018-05-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_rates', '0008_auto_20180529_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independentrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Call rate.'),
        ),
        migrations.AlterField(
            model_name='internationalhighrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Call rate.'),
        ),
        migrations.AlterField(
            model_name='internationallowrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Call rate.'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='canadian_ld_rate',
            field=models.DecimalField(decimal_places=4, default=0.02, max_digits=4, verbose_name='Canadian Long Distance Rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='inbound_rate',
            field=models.DecimalField(decimal_places=4, default=0.02, max_digits=4, verbose_name='Inbound Calling Rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='inbound_tollfree_rate',
            field=models.DecimalField(decimal_places=4, default=0.03, max_digits=4, verbose_name='Inbound Tollfree Calling Rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='international_ld_rate',
            field=models.DecimalField(decimal_places=4, default=0.02, max_digits=4, verbose_name='International Long Distance Rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='outbound_rate',
            field=models.DecimalField(decimal_places=4, default=0.02, max_digits=4, verbose_name='Outbound Calling Rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='united_states_ld_rate',
            field=models.DecimalField(decimal_places=4, default=0.02, max_digits=4, verbose_name='American Long Distance Rate'),
        ),
    ]
