# Generated by Django 2.0.3 on 2018-05-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_rates', '0009_auto_20180529_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCallingArea',
            fields=[
                ('exchange', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='The six-character exchange identifier.')),
                ('locality', models.CharField(max_length=96, verbose_name='The exchange location.')),
                ('local_calling_areas', models.CharField(default='[]', max_length=1024, verbose_name='An array of all the local calling areas by exchange identifier.')),
            ],
        ),
    ]
