# Generated by Django 2.0.3 on 2018-05-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_rates', '0010_localcallingarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcallingarea',
            name='local_calling_areas',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='An array of all the local calling areas by exchange identifier.'),
        ),
    ]
