# Generated by Django 2.0.3 on 2018-06-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_rates', '0011_auto_20180530_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='The rated month.')),
                ('call_charges', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Call Charges')),
                ('call_overages', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Call Charges')),
                ('accountcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdr_rates.Rate')),
            ],
        ),
    ]
