# Generated by Django 2.0.3 on 2018-07-01 23:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr_rates', '0013_auto_20180601_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('switch', models.CharField(max_length=80)),
                ('cdr_source_type', models.IntegerField(blank=True, editable=False, null=True)),
                ('callid', models.CharField(editable=False, max_length=80)),
                ('caller_id_number', models.CharField(editable=False, max_length=80, verbose_name='Caller ID Number')),
                ('caller_id_name', models.CharField(max_length=80, verbose_name='Caller ID')),
                ('destination_number', models.CharField(max_length=80, verbose_name='Dialed Number')),
                ('dialcode', models.CharField(blank=True, editable=False, max_length=10)),
                ('state', models.CharField(blank=True, editable=False, max_length=5)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('starting_date', models.DateTimeField(verbose_name='Date and Time')),
                ('duration', models.IntegerField()),
                ('billsec', models.IntegerField(editable=False)),
                ('progresssec', models.IntegerField(blank=True, editable=False, null=True)),
                ('answersec', models.IntegerField(blank=True, editable=False, null=True)),
                ('waitsec', models.IntegerField(blank=True, editable=False, null=True)),
                ('hangup_cause_id', models.IntegerField(blank=True, choices=[(0, 'Unspecified'), (1, 'Unallocated Number'), (2, 'No Route To Specified Transit Network'), (3, 'No Route To Destination'), (6, 'Channel Unacceptable'), (7, 'Call Awarded, Being Delivered In An Established Channel'), (16, 'Completed'), (17, 'User Busy'), (18, 'No User Response'), (19, 'No Answer'), (20, 'Subscriber Absent'), (21, 'Call Rejected'), (22, 'Number Changed'), (23, 'Redirected to New Destination'), (25, 'Exchange Routing Error'), (27, 'Destination Out of Order'), (28, 'Invalid Number Format'), (29, 'Facilities Rejected'), (30, 'Response to Status Inquiry'), (31, 'Completed, Unspecified'), (34, 'Circuit Congestion'), (38, 'Network Out of Order'), (41, 'Temporary Failure')], null=True, verbose_name='Hangup Cause')),
                ('hangup_cause', models.CharField(blank=True, editable=False, max_length=80)),
                ('direction', models.IntegerField(blank=True, choices=[(2, 'Outgoing'), (1, 'Incoming')], null=True)),
                ('country_code', models.CharField(blank=True, editable=False, max_length=3)),
                ('accountcode', models.CharField(blank=True, max_length=40, verbose_name='Account Code')),
                ('buy_rate', models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=10, null=True)),
                ('buy_cost', models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=12, null=True)),
                ('sell_rate', models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=10, null=True)),
                ('sell_cost', models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=12, null=True)),
                ('imported', models.BooleanField(default=False, editable=False)),
                ('extradata', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
            options={
                'verbose_name': 'CDR',
                'verbose_name_plural': 'CDRs',
                'db_table': 'cdr_import',
                'ordering': ['-starting_date'],
            },
        ),
    ]
